### ISSUE TITLE
Issue starting iSDI server on MacOS Monterey

### ISSUE THREAD

**Issue by adilahmed31** [stopipv/isdi#19]
By default, the current latest version of MacOS (Monterey) listens on port 5000 due to the new AirPlay functionality. This prevents isdi from being launched when run. 

Workaround is to disable AirPlay by turning off "Airplay Receiver" in the "Sharing" System Preference. 

Error:
```
TEST=False
Creating new db connection /Users/adil/Documents/IPV/isdi/data/fieldstudy.db
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app "web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "./isdi", line 26, in <module>
    app.run(host="0.0.0.0", port=PORT, debug=config.DEBUG)
  File "/Users/adil/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/Users/adil/opt/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 48] Address already in use
```

Checking running ports shows Control Center listening at ports 5000 and 7000.

```(base) xxxx@xxxxx-MacBook-Air isdi % sudo lsof -nP -iTCP -sTCP:LISTEN
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
---
adb       1676 xxxx    9u  IPv4 0xb21b2473ff6d05a9      0t0  TCP 127.0.0.1:5037 (LISTEN)
iproxy    1730 xxxx    3u  IPv4 0xb21b2474004b7b09      0t0  TCP 127.0.0.1:2222 (LISTEN)
iproxy    1730 xxxx    4u  IPv6 0xb21b24740bfe8151      0t0  TCP [::1]:2222 (LISTEN)
ControlCe 2288 xxxx   48u  IPv4 0xb21b247420213069      0t0  TCP *:7000 (LISTEN)
ControlCe 2288 xxxx   49u  IPv6 0xb21b24740bfe8f11      0t0  TCP *:7000 (LISTEN)
ControlCe 2288 xxxx   50u  IPv4 0xb21b24740f82a589      0t0  TCP *:5000 (LISTEN)
ControlCe 2288 xxxx   51u  IPv6 0xb21b24740bfe95f1      0t0  TCP *:5000 (LISTEN)
```

Disabling AirPlay receiver on MacOS fixes the issue, but the permanent fix would be to change the iSDI port number.

Ref: https://developer.apple.com/forums/thread/682332

**Comment by rchatterjee** [comment]
@adilahmed31 Can you submit a PR to address this issue? Use a larger port something like 8000 (maybe). Update the README as well, as necessary.   Thanks a lot!
