### ISSUE TITLE
  ImportError: cannot import name 'readPlist' from 'plistlib' (/usr/lib/python3.9/plistlib.py)

### ISSUE THREAD

**Issue by willemkuijpers** [stopipv/isdi#27]
ImportError

ImportError: cannot import name 'readPlist' from 'plistlib' (/usr/lib/python3.9/plistlib.py)
Traceback (most recent call last)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/ironx/isdi/web/view/scan.py", line 94, in scan

    device_name_print, device_name_map = sc.device_info(serial=ser)

    File "/home/ironx/isdi/phone_scanner.py", line 479, in device_info

    dumped = self._dump_phone(serial)

    File "/home/ironx/isdi/phone_scanner.py", line 505, in _dump_phone

    self.parse_dump = parse_dump.IosDump(dumpf, finfo=dumpfinfo)

    File "/home/ironx/isdi/parse_dump.py", line 365, in __init__

    self.deviceinfo = self.load_deviceinfo()

    File "/home/ironx/isdi/parse_dump.py", line 387, in load_deviceinfo

    from plistlib import readPlist

    ImportError: cannot import name 'readPlist' from 'plistlib' (/usr/lib/python3.9/plistlib.py)

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by willemkuijpers** [comment]
Devices found: ['00008101-000004160A51003A']
Devices: ['00008101-000004160A51003A']
>>>scanning_device ios 00008101-000004160A51003A <<<<<
idevicepair pair
DUMPING iOS INFO...
'/home/ironx/isdi/scripts/ios_dump.sh' b750fda36116af23c856d3cb19141edb9122a7e69abd9842cd6761df20b4a6f6 ios_apps.plist ios_info.xml ios_jailbroken.log ios_jailbreak_ssh.retcode
'/home/ironx/isdi/scripts/ios_dump.sh' b750fda36116af23c856d3cb19141edb9122a7e69abd9842cd6761df20b4a6f6 ios_apps.plist ios_info.xml ios_jailbroken.log ios_jailbreak_ssh.retcode
Returncode:  0

**Comment by shffrror** [comment]
This will be resolved with https://github.com/stopipv/isdi/pull/24

**Comment by lanamorgan** [comment]
Closed by merging in #24
