### ISSUE TITLE
Problems running isdi

### ISSUE THREAD

**Issue by adrianbone** [stopipv/isdi#51]
Hello, I followed instructions for Debian system but I get the following error when trying to run isdi.   Any ideas?

Traceback (most recent call last):
  File "/home/user/20082023/isdi/./isdi", line 9, in <module>
    from web import app, sa
  File "/home/user/20082023/isdi/web/__init__.py", line 22, in <module>
    import web.view
  File "/home/user/20082023/isdi/web/view/__init__.py", line 2, in <module>
    from .consult import client_forms, edit_forms
  File "/home/user/20082023/isdi/web/view/consult.py", line 4, in <module>
    from web.forms import ClientForm
  File "/home/user/20082023/isdi/web/forms/__init__.py", line 1, in <module>
    from .client import ClientForm
  File "/home/user/20082023/isdi/web/forms/client.py", line 1, in <module>
    from wtforms_alchemy import ModelForm
  File "/usr/local/lib/python3.11/dist-packages/wtforms_alchemy/__init__.py", line 40, in <module>
    from .validators import Unique  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wtforms_alchemy/validators.py", line 1, in <module>
    from collections import Iterable, Mapping
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by drpomeranus** [comment]
If you're using python 3.11, you need a more recent wtforms_alchemy version. Try replacing WTForms-Alchemy==0.16.9 with WTForms-Alchemy==0.18.0 in the requirements.txt, that worked for me at least

**Comment by naman** [comment]
@adrianbone are you still facing an issue with running isdi?
