### ISSUE TITLE
KeyError:  'appId'

### ISSUE THREAD

**Issue by karminer60** [stopipv/isdi#64]
When I run ./isdi I get this error:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/isdi/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/web/view/scan.py", line 123, in scan
    apps = sc.find_spyapps(serialno=ser, from_dump=from_dump).fillna('').to_dict(orient='index')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/phone_scanner.py", line 119, in find_spyapps
    installed_apps = self.get_apps(serialno, from_device=from_device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/phone_scanner.py", line 464, in get_apps
    self.installed_apps = self.parse_dump.installed_apps()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/parse_dump.py", line 585, in installed_apps
    return self.df['appId'].to_list()
           ~~~~~~~^^^^^^^^^
  File "/home/ubuntu/isdi/venv/lib/python3.11/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/isdi/venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'appId'

**Comment by moshiba** [comment]
I'm getting this too.

Environment:
- macOS 15.1.1 (24B91) on M1 MacBook Pro
- python 3.10.15
- iOS 18.1 (22B83) on iPhone 12
- isdi version: commit d7b081f

**Comment by rchatterjee** [comment]
This should be fixed now. Can you try again?

**Comment by moshiba** [comment]
it works!

Environment:
- macOS 15.1.1 (24B91) on M1 MacBook Pro
- python 3.9.21
- iOS 18.1.1 (22B91) on iPhone 12
- isdi version: commit 018303b9cb275bd7a65957b2752e4617cadcf5cc
